/** Declaration file generated by dts-gen */

export = ml_regression_multivariate_linear;

declare class ml_regression_multivariate_linear {
    constructor(...args: any[]);

    predict(...args: any[]): any;

    score(...args: any[]): any;

    toJSON(...args: any[]): any;

    static load(...args: any[]): any;

}

