/** Declaration file generated by dts-gen */

export = ml_regression_multivariate_linear;

declare class ml_regression_multivariate_linear {
    constructor(...args: any[]);

    predict(...args: any[]): void;

    score(...args: any[]): void;

    toJSON(...args: any[]): void;

    static load(...args: any[]): void;

}

